server:
  port: 8080
  servlet:
    context-path: /tk-recommendations
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: tk-recommendations
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-ui
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: false

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=50,expireAfterWrite=30m

  datasource:
    transaction:
        read-only: true
        jdbc-url: jdbc:h2:file:./src/main/resources/db/transaction_orig
        username: ''
        password: ''
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
    # CREATE DATABASE tk_recommendations;
    # CREATE USER recommendations_god WITH LOGIN PASSWORD '87654321';
    # ALTER DATABASE tk_recommendations OWNER TO recommendations_god ;
    recommendation:
        jdbc-url: jdbc:postgresql://localhost:5432/tk_recommendations
        username: recommendations_god
        password: 87654321
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog-master.yml
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/tk_recommendations
      user: recommendations_god
      password: 87654321

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
